name: qvid
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player:
  cached_video_player:
  percent_indicator: ^2.1.5
  carousel_slider: ^2.1.0
  flutter_phoenix: ^0.1.0
  emoji_picker: ^0.1.0
  google_fonts:
  flutter_facebook_login: ^3.0.0
  http:
  shared_preferences:
  cached_network_image:
  image_picker:
  flutter_uploader:
  pull_to_refresh:
  fluttertoast:
  timeago:
  flutter_web_view:
  fitted_text_field_container:
  pin_code_fields:
  sliding_up_panel:
  datetime_picker_formfield:
  camera: ^0.5.8+5
  flashlight: ^0.1.1
  image_cropper:
  permission_handler:
  just_audio:
  clipboard_manager:
  dio:
  file_picker: ^2.0.0
  gallery_saver:
  flutter_ffmpeg: ^0.3.0
#  flutter_ffmpeg:
#    git:
#      url: git://github.com/tanersener/flutter-ffmpeg.git
#      ref: v0.1.1
#      path: packages/flutter_ffmpeg_full-gpl_lts
  path_provider: ^1.6.5
  chewie:

   # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/icons/
    - assets/user/
    - assets/thumbnails/dance/
    - assets/thumbnails/lol/
    - assets/thumbnails/food/