name: qvid
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player:
  cached_video_player:
  carousel_slider: ^2.1.0
  flutter_phoenix: ^0.1.0
  google_fonts:
  flutter_facebook_login: ^3.0.0
  http:
  shared_preferences:
  cached_network_image:
  image_picker:
  flutter_uploader:
  pull_to_refresh:
  fluttertoast: ^7.1.1
  timeago:
  flutter_web_view:
  pin_code_fields:
  datetime_picker_formfield:
  visibility_detector:
  flutter_better_camera:
  lamp:
  torch_compat:
  image_cropper:
  permission_handler:
  just_audio:
  matrix_gesture_detector:
  matrix4_transform:
  clipboard_manager:
  dio:
  file_picker: ^2.0.0
  gallery_saver:
  flutter_ffmpeg: ^0.3.0
  path_provider: ^1.6.5
  media_info:
  screenshot:
  flutter_xlider:
  flutter_cache_manager:
  image: ^2.1.18
  palette_generator:
  tapioca:
  overlay_support:
  firebase_messaging:



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/icons/
    - assets/user/
    - assets/others/


  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
